name: coffeetek_pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.18.0
  google_fonts: ^6.1.0
  http: ^1.6.0
  printing: ^5.14.2
  pdf: ^3.11.3
  shared_preferences: ^2.5.3
  presentation_displays: ^1.0.0
  desktop_multi_window: ^0.2.0
  window_manager: ^0.5.1
  html: ^0.15.6
  # http hoáº·c dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
